DROP DATABASE IF EXSISTS 'EMPLOYEE_DB';
CREATE DATABASE 'EMPLOYEE_DB';

CREATE TABLE 'DEPARTMENT' (
    'DEPARTMENT_ID' SERIAL PRIMARY KEY,
    'DEPARTMENT_NAME' VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE 'ROLE' (
    'ROLE_ID' SERIAL PRIMARY KEY,
    'ROLE_TITLE' VARCHAR(30) UNIQUE NOT NULL,
    'ROLE_SALARY' DECIMAL NOT NULL
    'ROLE_NAME' VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE 'EMPLOYEE' (
    'EMPLOYEE_ID' SERIAL PRIMARY KEY,
    'EMPLOYEE_FIRST_NAME' VARCHAR(30) NOT NULL,
    'EMPLOYEE_LAST_NAME' VARCHAR(30) NOT NULL,
    'ROLE_ID' INTEGER NOT NULL,
    'MANAGER_ID' INTEGER, ELSE NULL);